### ISSUE TITLE
Warnings with Java 9, Clojure 1.9.0, and lein 2.8.1

### ISSUE THREAD

**Issue by neverfox** [xsc/lein-ancient#91] opened 2018-01-01 01:43 UTC
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by clojure.lang.Reflector (file:/usr/local/Cellar/leiningen/2.8.1/libexec/leiningen-2.8.1-standalone.jar) to method com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(java.io.Reader)
WARNING: Please consider reporting this to the maintainers of clojure.lang.Reflector
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
all artifacts are up-to-date.
```

I do not get this warning with other lein commands, e.g. lein repl.

**Comment by xsc** [comment] 2018-01-02 10:36
@neverfox Thanks for reporting! I think the root cause is `clojure.data.xml` calling that method ([here](https://github.com/clojure/data.xml/blob/data.xml-0.0.8/src/main/clojure/clojure/data/xml.clj#L337)), as well as Clojure's reflection behaviour.

A quick fix could be switching to a different XML parsing library but I'd rather see this resolved in Clojure itself. [CLJ-2066](https://dev.clojure.org/jira/browse/CLJ-2066) seems to be the relevant issue.

**Comment by lread** [comment] 2019-01-06 22:20
Hi there, CLJ-2066 was resolved with Clojure 1.10 release.  Any advice on how to quash these warnings under OpenJDK 11?

**Comment by j-cr** [comment] 2019-12-23 08:43
Slightly different warnings (lein-ancient 0.6.15, clojure 1.10.*):

```
> lein version
Leiningen 2.9.1 on Java 11.0.5 OpenJDK 64-Bit Server VM 
> lein ancient
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by clojure.lang.InjectedInvoker/0x0000000100062840 to method com.sun.xml.internal.stream.XMLInputFactoryImpl.createXMLStreamReader(java.io.InputStream)
WARNING: Please consider reporting this to the maintainers of clojure.lang.InjectedInvoker/0x0000000100062840
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
all artifacts are up-to-date.

```

**Comment by superstructor** [comment] 2020-09-14 19:22
This appears to be fixed by upgrading `org.clojure/data.xml` in `ancient-clj/project.clj` to `0.2.0-alpha6` (latest available). @xsc

**Comment by superstructor** [comment] 2020-11-11 20:33
@xsc I've opened a pull request with the change. If you could please merge and release w/ associated upgrade of the ancient-clj version in the plugin's project.clj it would help clean up terminals everywhere!

**Comment by lread** [comment] 2020-11-19 15:17
@superstructor, [antq](https://github.com/liquidz/antq) is actively maintained and might be an interesting alternative for you to check out. I am happily using it for my tools deps projects.

**Closed** 2020-12-21 11:26 UTC
