### ISSUE TITLE
alpha version checking

### ISSUE THREAD

**Issue by kanwei** [xsc/lein-ancient#74] opened 2016-05-16 16:24 UTC
[org.webjars.bower/bootstrap "4.0.0-alpha.2"] is available but we use "3.3.6"

even without :allow-qualified

**Comment by xsc** [comment] 2016-08-22 08:13
@kanwei Sorry for the delayed response. This is caused by version-clj's splitting of version strings by first `.`, then `-`:

```clojure
"4.0.0-alpha.2" => [[4] [0] [0 "alpha"] [2]]
```

The qualifier is expected to appear in the last element of the version vector but in this case doesn't. I'm not sure this can be fixed without breaking behaviour for versions like `"9.1-901-1.jdbc4"`, though, but feel free to open an issue at version-clj.

**Closed** 2017-09-14 10:27 UTC
Labels: upstream
