### ISSUE TITLE
Pinned com.amazonaws/aws-java-sdk-s3 is too ancient

### ISSUE THREAD

**Issue by huahaiy** [xsc/lein-ancient#82] opened 2017-10-27 06:01 UTC
Make lein-ancient unusable on any project that uses aws-java-sdk-s3, which is plenty.

**Comment by xsc** [comment] 2017-10-27 06:44
@huahaiy Thanks for reporting this! Can you tell me what behaviour you're seeing, i.e. is there an exception thrown by lein-ancient or does Leiningen's dependency resolution complain? Or is it overwriting your project's dependencies?

**Comment by huahaiy** [comment] 2017-10-27 07:24
With lein-ancient in the ./lein/profiles.clj, it overwrites the project's dependencies on aws libraries, and code depends on that library would throw method not found exceptions, mainly due to the old jackson used in the old aws library:

e.g. run lein ancient

(warn)  [private] - Δ  810ms - failure when checking com.layerware/hugsql: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  819ms - failure when checking clojure-csv/clojure-csv: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  811ms - failure when checking clj-time/clj-time: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  819ms - failure when checking clj-aws-s3/clj-aws-s3: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  812ms - failure when checking org.clojure/java.jdbc: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  812ms - failure when checking kafka-component/kafka-component: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  818ms - failure when checking clj-kafka/clj-kafka: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  810ms - failure when checking postgres-component/postgres-component: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  817ms - failure when checking ring/ring-codec: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  810ms - failure when checking org.twitter4j/twitter4j-core: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  816ms - failure when checking org.clojure/clojure: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  810ms - failure when checking com.googlecode.json-simple/json-simple: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  814ms - failure when checking com.fasterxml.jackson.core/jackson-databind: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  812ms - failure when checking cheshire/cheshire: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  816ms - failure when checking org.clojure/tools.cli: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  816ms - failure when checking com.taoensso/timbre: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  813ms - failure when checking environ/environ: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  813ms - failure when checking com.stuartsierra/component: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
(warn)  [private] - Δ  850ms - failure when checking enlive/enlive: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z

**Comment by xsc** [comment] 2017-10-27 08:27
Just to be sure: Which Leiningen version are you using (`lein version`)?

**Comment by huahaiy** [comment] 2017-10-27 19:28
Leiningen 2.7.1 on Java 1.8.0_152 Java HotSpot(TM) 64-Bit Server VM

**Comment by timgilbert** [comment] 2017-10-27 19:49
I'm also seeing some kind AWS-related error with lein 2.8.0 / OS/X / Java 1.8.0_152, but unfortunately I can't be sure whether it's related to this. The error I see is 

```
clojure.lang.Compiler$CompilerException: java.lang.ClassNotFoundException: com.amazonaws.services.s3.AmazonS3ClientBuilder, compiling:(ancient/ancient_clj/v0v6v14/ancient_clj/io/s3.clj:1:1)
 at clojure.lang.Compiler.load (Compiler.java:7391)
    clojure.lang.RT.loadResourceScript (RT.java:372)
[...]
    clojure.lang.RestFn.invoke (RestFn.java:457)
    ancient.ancient_clj.v0v6v14.ancient_clj.io$eval3935$loading__5569__auto____3936.invoke (io.clj:1)
    ancient.ancient_clj.v0v6v14.ancient_clj.io$eval3935.invokeStatic (io.clj:1)
    ancient.ancient_clj.v0v6v14.ancient_clj.io$eval3935.invoke (io.clj:1)
    clojure.lang.Compiler.eval (Compiler.java:6927)
```

Possibly related, lein itself has some AWS dependencies which were updated in 2.8.0: https://github.com/technomancy/leiningen/issues/2215

**Comment by xsc** [comment] 2017-12-03 11:21
@huahaiy I could reproduce your issue but it doesn't seem to be lein-ancient's dependencies that causes these problems but Leiningen's. I tried the following `project.clj`, pointing at a nonsense S3 repository:

```clojure
(defproject aws-test "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.8.0"]]
  :repositories {"private" "s3p://localhost/bucket"})
```

This is the output of `DEBUG=1 lein ancient` with Leiningen 2.7.1:

```
(warn)  [private] - Δ  180ms - failure when checking org.clojure/clojure: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.JavaType.isReferenceType()Z
all artifacts are up-to-date.
```

And this is the output with Leiningen 2.8.1:

```
(warn)  [private] - Δ 7968ms - failure when checking org.clojure/clojure: com.amazonaws.AmazonClientException: Unable to load region information from any provider in the chain
all artifacts are up-to-date.
```

From what I can see, the outdated Jackson library came from `cheshire` which is no longer a direct Leiningen dependency starting with version 2.8.0 (see the issue that @timgilbert linked above).

---

@timgilbert Could you print the output of `lein deps :plugin-tree` when called within the project that caused the error you mentioned? Maybe some other plugin is overriding the S3 dependency.

**Comment by timgilbert** [comment] 2017-12-27 15:04
Sorry for the late response! I eventually tracked my issue down to an issue with the `lein-essthree` plugin, which has since released a new version that fixed my issue.

**Comment by xsc** [comment] 2017-12-28 12:20
@timgilbert Good to hear that this has been resolved for you!

@huahaiy I'll close this issue since it doesn't seem to be caused by lein-ancient. Feel free to reopen if you think that's not true!

**Closed by xsc** 2017-12-28 12:20 UTC
Labels: compatibility
